### ISSUE TITLE
Prelease Version: Black Background instead of Blue After Battle EXP Screen

### ISSUE THREAD

**Issue by PAZLAPROV** [Legend-of-Dragoon-Modding/Severed-Chains#1206]
Amazing work and I know that its still being worked on but, I just want to report things in case they arent correct.

Also is there a higher FPS for battles coming soon?

**Comment by DrewUniverse** [comment]
Yes, but not for some time. 60FPS for battle requires a separate build since it's a lot of work. The current plan is as follows:

- Recommended Build 3: 60FPS everywhere else, native 4K resolution, hardware rendering, true widescreen in battle and world map.
- RB4: expansion of the modding API.
- RB5: 60FPS battles.
