### ISSUE TITLE
No Pause Menu in World Map

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1482]
This occurred just after beating the Divine Dragon. Couldn't open on the road to Evergreen Forest, and after going through the forest I couldn't open it on the road to Deningrad. Entering and exiting locations did not fix this issue.

**Comment by howdagee** [comment]
@Zychronix just want to add that I noticed this issue as well, but in a different area. Not sure if this is specific to sections of the world map or what because I hadn't tried to open it before until now. I was making my way to Indels castle (after beating the snake boss from the early Cave) and noticed it. Not sure if it is specific to this area.
![cf2b1507-7096-49d9-af0b-b657a5d32085](https://github.com/user-attachments/assets/7127cccf-721e-4ae4-b8cd-e8af462de957)

**Comment by LordMonoxide** [comment]
From what I've seen, it isn't tied to a specific area. If anyone can reproduce this while running the game from source code, please stay exactly where you are ingame and let me know immediately so we can inspect the game vars while the game is still running
