### ISSUE TITLE
Automatic save conversion does not allow you to choose other options

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#1644]
Not technically a bug, but having the converter skip the main menu and start automatically feels awkward to use. If someone would rather just start a new game or go into options first, they can't. The process even gives the option to cancel, but doing so just loops back through the title screen before dumping the user right back into the conversion popup.

It would be preferable if the conversion screen did not occur until Continue is selected, since converting a memcard is not relevant to the other title screen options. Cancel should likewise take you back to the title menu.

**Comment by LordMonoxide** [comment]
- Add two new properties to Ttle, `memcardConversionShown` and `saveCategorizationShown`
- Set these flags in `renderMenuOptions` inside of the first two if statements
- Add an && condition to both statements to check if those were already set

It would also be nice to add menu options to reopen these menus if the user closed them, but that'd be a lot more work. The texture for the menu buttons is at `gfx/ui/5718_3.png`. We use an edited version because we changed "New Game" to "New Campaign", and you'd have to match the font and blur.
